import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

/**
 * This started as the config Lovable generated for a single-page React app,
 * and the repository stopped being one. Two consequences had to be fixed
 * before `npm run lint` could pass:
 *
 * **The React rules applied to everything.** `react-hooks` and
 * `react-refresh` were on for every `.ts` file in the monorepo, including the
 * Fastify API, the seed scripts and the Playwright suite. They are meaningless
 * there, and one of them was actively wrong: Playwright's fixture callback
 * takes a function called `use`, which `react-hooks/rules-of-hooks` reads as
 * React's `use` hook being called outside a component. The rule was right
 * about what it saw and wrong about what it was looking at.
 *
 * **Every file was given browser globals.** `window` and `document` do not
 * exist in the API, and `process` does — the reverse of what was configured.
 *
 * So the config is now scoped by area, which is also how the `.prettierrc`
 * overrides are arranged: `apps/web` is Lovable's code and keeps its
 * conventions, and everything written since follows its own.
 */
export default tseslint.config(
  {
    ignores: [
      // Retired code kept for the record only — MySQL-era scripts and
      // migrations superseded by the move to PostgreSQL (D43). It is not
      // runnable against this schema and is not maintained.
      "docs/archive/**",
      "**/dist/**",
      "**/.output/**",
      "**/.vinxi/**",
      "**/coverage/**",
      "**/build/**",
      "apps/api/prisma/generated/**",
      "playwright-report/**",
      "test-results/**",
      // Generated by TanStack Router on every dev start.
      "apps/web/src/routeTree.gen.ts",
    ],
  },

  // --- Everything TypeScript --------------------------------------------
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx,mjs}"],
    languageOptions: { ecmaVersion: 2022 },
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      // Handled by the compiler, which reports it with better context.
      "@typescript-eslint/no-unused-vars": "off",
    },
  },

  // --- The browser ------------------------------------------------------
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    languageOptions: { globals: globals.browser },
    plugins: { "react-hooks": reactHooks, "react-refresh": reactRefresh },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
    },
  },

  // --- Node: the API, its scripts and seeds, and the operational scripts --
  {
    files: ["apps/api/**/*.ts", "packages/**/*.ts", "scripts/**/*.mjs"],
    languageOptions: { globals: globals.node },
  },

  // --- Playwright --------------------------------------------------------
  {
    files: ["e2e/**/*.ts", "playwright.config.ts"],
    languageOptions: { globals: globals.node },
    rules: {
      /**
       * `async ({}, use) => …` is Playwright's own fixture signature. The
       * empty pattern is how you declare a fixture that depends on no other
       * fixture, so it is idiomatic rather than an oversight.
       */
      "no-empty-pattern": "off",
    },
  },

  eslintPluginPrettier,
);
