/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorOnboardingRouteImport } from './routes/doctor.onboarding'
import { Route as DoctorQueueRouteImport } from './routes/doctor.queue'
import { Route as OnboardingDoctorRouteImport } from './routes/onboarding.doctor'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PharmacyIndexRouteImport } from './routes/pharmacy.index'
import { Route as PharmacyNewRouteImport } from './routes/pharmacy.new'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as DoctorConsultationsPublicIdRouteImport } from './routes/doctor.consultations.$publicId'
import { Route as PharmacyConsultationsPublicIdRouteImport } from './routes/pharmacy.consultations.$publicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/admin/queue',
  path: '/admin/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorOnboardingRoute = DoctorOnboardingRouteImport.update({
  id: '/doctor/onboarding',
  path: '/doctor/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorQueueRoute = DoctorQueueRouteImport.update({
  id: '/doctor/queue',
  path: '/doctor/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDoctorRoute = OnboardingDoctorRouteImport.update({
  id: '/onboarding/doctor',
  path: '/onboarding/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyIndexRoute = PharmacyIndexRouteImport.update({
  id: '/pharmacy/',
  path: '/pharmacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyNewRoute = PharmacyNewRouteImport.update({
  id: '/pharmacy/new',
  path: '/pharmacy/new',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationsPublicIdRoute =
  DoctorConsultationsPublicIdRouteImport.update({
    id: '/doctor/consultations/$publicId',
    path: '/doctor/consultations/$publicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PharmacyConsultationsPublicIdRoute =
  PharmacyConsultationsPublicIdRouteImport.update({
    id: '/pharmacy/consultations/$publicId',
    path: '/pharmacy/consultations/$publicId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/auth/login': typeof AuthLoginRoute
  '/doctor/onboarding': typeof DoctorOnboardingRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/onboarding/doctor': typeof OnboardingDoctorRoute
  '/pharmacy/new': typeof PharmacyNewRoute
  '/s/$token': typeof STokenRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/doctor/consultations/$publicId': typeof DoctorConsultationsPublicIdRoute
  '/pharmacy/consultations/$publicId': typeof PharmacyConsultationsPublicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/auth/login': typeof AuthLoginRoute
  '/doctor/onboarding': typeof DoctorOnboardingRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/onboarding/doctor': typeof OnboardingDoctorRoute
  '/pharmacy/new': typeof PharmacyNewRoute
  '/s/$token': typeof STokenRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/pharmacy': typeof PharmacyIndexRoute
  '/doctor/consultations/$publicId': typeof DoctorConsultationsPublicIdRoute
  '/pharmacy/consultations/$publicId': typeof PharmacyConsultationsPublicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/auth/login': typeof AuthLoginRoute
  '/doctor/onboarding': typeof DoctorOnboardingRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/onboarding/doctor': typeof OnboardingDoctorRoute
  '/pharmacy/new': typeof PharmacyNewRoute
  '/s/$token': typeof STokenRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/doctor/consultations/$publicId': typeof DoctorConsultationsPublicIdRoute
  '/pharmacy/consultations/$publicId': typeof PharmacyConsultationsPublicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/queue'
    | '/admin/verification'
    | '/auth/login'
    | '/doctor/onboarding'
    | '/doctor/queue'
    | '/onboarding/doctor'
    | '/pharmacy/new'
    | '/s/$token'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/pharmacy/'
    | '/doctor/consultations/$publicId'
    | '/pharmacy/consultations/$publicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/queue'
    | '/admin/verification'
    | '/auth/login'
    | '/doctor/onboarding'
    | '/doctor/queue'
    | '/onboarding/doctor'
    | '/pharmacy/new'
    | '/s/$token'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/pharmacy'
    | '/doctor/consultations/$publicId'
    | '/pharmacy/consultations/$publicId'
  id:
    | '__root__'
    | '/'
    | '/admin/queue'
    | '/admin/verification'
    | '/auth/login'
    | '/doctor/onboarding'
    | '/doctor/queue'
    | '/onboarding/doctor'
    | '/pharmacy/new'
    | '/s/$token'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/pharmacy/'
    | '/doctor/consultations/$publicId'
    | '/pharmacy/consultations/$publicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DoctorOnboardingRoute: typeof DoctorOnboardingRoute
  DoctorQueueRoute: typeof DoctorQueueRoute
  OnboardingDoctorRoute: typeof OnboardingDoctorRoute
  PharmacyNewRoute: typeof PharmacyNewRoute
  STokenRoute: typeof STokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PharmacyIndexRoute: typeof PharmacyIndexRoute
  DoctorConsultationsPublicIdRoute: typeof DoctorConsultationsPublicIdRoute
  PharmacyConsultationsPublicIdRoute: typeof PharmacyConsultationsPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/admin/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/onboarding': {
      id: '/doctor/onboarding'
      path: '/doctor/onboarding'
      fullPath: '/doctor/onboarding'
      preLoaderRoute: typeof DoctorOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/queue': {
      id: '/doctor/queue'
      path: '/doctor/queue'
      fullPath: '/doctor/queue'
      preLoaderRoute: typeof DoctorQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/doctor': {
      id: '/onboarding/doctor'
      path: '/onboarding/doctor'
      fullPath: '/onboarding/doctor'
      preLoaderRoute: typeof OnboardingDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/': {
      id: '/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof PharmacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/new': {
      id: '/pharmacy/new'
      path: '/pharmacy/new'
      fullPath: '/pharmacy/new'
      preLoaderRoute: typeof PharmacyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultations/$publicId': {
      id: '/doctor/consultations/$publicId'
      path: '/doctor/consultations/$publicId'
      fullPath: '/doctor/consultations/$publicId'
      preLoaderRoute: typeof DoctorConsultationsPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/consultations/$publicId': {
      id: '/pharmacy/consultations/$publicId'
      path: '/pharmacy/consultations/$publicId'
      fullPath: '/pharmacy/consultations/$publicId'
      preLoaderRoute: typeof PharmacyConsultationsPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AuthLoginRoute: AuthLoginRoute,
  DoctorOnboardingRoute: DoctorOnboardingRoute,
  DoctorQueueRoute: DoctorQueueRoute,
  OnboardingDoctorRoute: OnboardingDoctorRoute,
  PharmacyNewRoute: PharmacyNewRoute,
  STokenRoute: STokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  PharmacyIndexRoute: PharmacyIndexRoute,
  DoctorConsultationsPublicIdRoute: DoctorConsultationsPublicIdRoute,
  PharmacyConsultationsPublicIdRoute: PharmacyConsultationsPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
