/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminArchiveRouteImport } from './routes/admin.archive'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminPayrollRouteImport } from './routes/admin.payroll'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminQualityRouteImport } from './routes/admin.quality'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminSchedulingRouteImport } from './routes/admin.scheduling'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorEarningsRouteImport } from './routes/doctor.earnings'
import { Route as DoctorMembershipRouteImport } from './routes/doctor.membership'
import { Route as DoctorOnboardingRouteImport } from './routes/doctor.onboarding'
import { Route as DoctorQueueRouteImport } from './routes/doctor.queue'
import { Route as DoctorSubstitutionsRouteImport } from './routes/doctor.substitutions'
import { Route as OnboardingDoctorRouteImport } from './routes/onboarding.doctor'
import { Route as OnboardingPharmacyRouteImport } from './routes/onboarding.pharmacy'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PharmacyIndexRouteImport } from './routes/pharmacy.index'
import { Route as PharmacyFinanceRouteImport } from './routes/pharmacy.finance'
import { Route as PharmacyNewRouteImport } from './routes/pharmacy.new'
import { Route as PharmacyOnboardingRouteImport } from './routes/pharmacy.onboarding'
import { Route as PharmacyPrescriptionsRouteImport } from './routes/pharmacy.prescriptions'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as DoctorConsultationsPublicIdRouteImport } from './routes/doctor.consultations.$publicId'
import { Route as PharmacyConsultationsPublicIdRouteImport } from './routes/pharmacy.consultations.$publicId'
import { Route as VerifyKindCodeRouteImport } from './routes/verify.$kind.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArchiveRoute = AdminArchiveRouteImport.update({
  id: '/admin/archive',
  path: '/admin/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/admin/payroll',
  path: '/admin/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/admin/promotions',
  path: '/admin/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQualityRoute = AdminQualityRouteImport.update({
  id: '/admin/quality',
  path: '/admin/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/admin/queue',
  path: '/admin/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchedulingRoute = AdminSchedulingRouteImport.update({
  id: '/admin/scheduling',
  path: '/admin/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorEarningsRoute = DoctorEarningsRouteImport.update({
  id: '/doctor/earnings',
  path: '/doctor/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorMembershipRoute = DoctorMembershipRouteImport.update({
  id: '/doctor/membership',
  path: '/doctor/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorOnboardingRoute = DoctorOnboardingRouteImport.update({
  id: '/doctor/onboarding',
  path: '/doctor/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorQueueRoute = DoctorQueueRouteImport.update({
  id: '/doctor/queue',
  path: '/doctor/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSubstitutionsRoute = DoctorSubstitutionsRouteImport.update({
  id: '/doctor/substitutions',
  path: '/doctor/substitutions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDoctorRoute = OnboardingDoctorRouteImport.update({
  id: '/onboarding/doctor',
  path: '/onboarding/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPharmacyRoute = OnboardingPharmacyRouteImport.update({
  id: '/onboarding/pharmacy',
  path: '/onboarding/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyIndexRoute = PharmacyIndexRouteImport.update({
  id: '/pharmacy/',
  path: '/pharmacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyFinanceRoute = PharmacyFinanceRouteImport.update({
  id: '/pharmacy/finance',
  path: '/pharmacy/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyNewRoute = PharmacyNewRouteImport.update({
  id: '/pharmacy/new',
  path: '/pharmacy/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyOnboardingRoute = PharmacyOnboardingRouteImport.update({
  id: '/pharmacy/onboarding',
  path: '/pharmacy/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyPrescriptionsRoute = PharmacyPrescriptionsRouteImport.update({
  id: '/pharmacy/prescriptions',
  path: '/pharmacy/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationsPublicIdRoute =
  DoctorConsultationsPublicIdRouteImport.update({
    id: '/doctor/consultations/$publicId',
    path: '/doctor/consultations/$publicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PharmacyConsultationsPublicIdRoute =
  PharmacyConsultationsPublicIdRouteImport.update({
    id: '/pharmacy/consultations/$publicId',
    path: '/pharmacy/consultations/$publicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyKindCodeRoute = VerifyKindCodeRouteImport.update({
  id: '/verify/$kind/$code',
  path: '/verify/$kind/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/archive': typeof AdminArchiveRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/scheduling': typeof AdminSchedulingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/doctor/earnings': typeof DoctorEarningsRoute
  '/doctor/membership': typeof DoctorMembershipRoute
  '/doctor/onboarding': typeof DoctorOnboardingRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/substitutions': typeof DoctorSubstitutionsRoute
  '/onboarding/doctor': typeof OnboardingDoctorRoute
  '/onboarding/pharmacy': typeof OnboardingPharmacyRoute
  '/pharmacy/finance': typeof PharmacyFinanceRoute
  '/pharmacy/new': typeof PharmacyNewRoute
  '/pharmacy/onboarding': typeof PharmacyOnboardingRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/s/$token': typeof STokenRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/doctor/consultations/$publicId': typeof DoctorConsultationsPublicIdRoute
  '/pharmacy/consultations/$publicId': typeof PharmacyConsultationsPublicIdRoute
  '/verify/$kind/$code': typeof VerifyKindCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/archive': typeof AdminArchiveRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/scheduling': typeof AdminSchedulingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/doctor/earnings': typeof DoctorEarningsRoute
  '/doctor/membership': typeof DoctorMembershipRoute
  '/doctor/onboarding': typeof DoctorOnboardingRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/substitutions': typeof DoctorSubstitutionsRoute
  '/onboarding/doctor': typeof OnboardingDoctorRoute
  '/onboarding/pharmacy': typeof OnboardingPharmacyRoute
  '/pharmacy/finance': typeof PharmacyFinanceRoute
  '/pharmacy/new': typeof PharmacyNewRoute
  '/pharmacy/onboarding': typeof PharmacyOnboardingRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/s/$token': typeof STokenRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/pharmacy': typeof PharmacyIndexRoute
  '/doctor/consultations/$publicId': typeof DoctorConsultationsPublicIdRoute
  '/pharmacy/consultations/$publicId': typeof PharmacyConsultationsPublicIdRoute
  '/verify/$kind/$code': typeof VerifyKindCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/archive': typeof AdminArchiveRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/scheduling': typeof AdminSchedulingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/doctor/earnings': typeof DoctorEarningsRoute
  '/doctor/membership': typeof DoctorMembershipRoute
  '/doctor/onboarding': typeof DoctorOnboardingRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/substitutions': typeof DoctorSubstitutionsRoute
  '/onboarding/doctor': typeof OnboardingDoctorRoute
  '/onboarding/pharmacy': typeof OnboardingPharmacyRoute
  '/pharmacy/finance': typeof PharmacyFinanceRoute
  '/pharmacy/new': typeof PharmacyNewRoute
  '/pharmacy/onboarding': typeof PharmacyOnboardingRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/s/$token': typeof STokenRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/doctor/consultations/$publicId': typeof DoctorConsultationsPublicIdRoute
  '/pharmacy/consultations/$publicId': typeof PharmacyConsultationsPublicIdRoute
  '/verify/$kind/$code': typeof VerifyKindCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/archive'
    | '/admin/audit'
    | '/admin/payouts'
    | '/admin/payroll'
    | '/admin/promotions'
    | '/admin/quality'
    | '/admin/queue'
    | '/admin/refunds'
    | '/admin/scheduling'
    | '/admin/settings'
    | '/admin/verification'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/doctor/earnings'
    | '/doctor/membership'
    | '/doctor/onboarding'
    | '/doctor/queue'
    | '/doctor/substitutions'
    | '/onboarding/doctor'
    | '/onboarding/pharmacy'
    | '/pharmacy/finance'
    | '/pharmacy/new'
    | '/pharmacy/onboarding'
    | '/pharmacy/prescriptions'
    | '/s/$token'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/pharmacy/'
    | '/doctor/consultations/$publicId'
    | '/pharmacy/consultations/$publicId'
    | '/verify/$kind/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/archive'
    | '/admin/audit'
    | '/admin/payouts'
    | '/admin/payroll'
    | '/admin/promotions'
    | '/admin/quality'
    | '/admin/queue'
    | '/admin/refunds'
    | '/admin/scheduling'
    | '/admin/settings'
    | '/admin/verification'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/doctor/earnings'
    | '/doctor/membership'
    | '/doctor/onboarding'
    | '/doctor/queue'
    | '/doctor/substitutions'
    | '/onboarding/doctor'
    | '/onboarding/pharmacy'
    | '/pharmacy/finance'
    | '/pharmacy/new'
    | '/pharmacy/onboarding'
    | '/pharmacy/prescriptions'
    | '/s/$token'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/pharmacy'
    | '/doctor/consultations/$publicId'
    | '/pharmacy/consultations/$publicId'
    | '/verify/$kind/$code'
  id:
    | '__root__'
    | '/'
    | '/admin/archive'
    | '/admin/audit'
    | '/admin/payouts'
    | '/admin/payroll'
    | '/admin/promotions'
    | '/admin/quality'
    | '/admin/queue'
    | '/admin/refunds'
    | '/admin/scheduling'
    | '/admin/settings'
    | '/admin/verification'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/doctor/earnings'
    | '/doctor/membership'
    | '/doctor/onboarding'
    | '/doctor/queue'
    | '/doctor/substitutions'
    | '/onboarding/doctor'
    | '/onboarding/pharmacy'
    | '/pharmacy/finance'
    | '/pharmacy/new'
    | '/pharmacy/onboarding'
    | '/pharmacy/prescriptions'
    | '/s/$token'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/pharmacy/'
    | '/doctor/consultations/$publicId'
    | '/pharmacy/consultations/$publicId'
    | '/verify/$kind/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminArchiveRoute: typeof AdminArchiveRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminQualityRoute: typeof AdminQualityRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminSchedulingRoute: typeof AdminSchedulingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  DoctorEarningsRoute: typeof DoctorEarningsRoute
  DoctorMembershipRoute: typeof DoctorMembershipRoute
  DoctorOnboardingRoute: typeof DoctorOnboardingRoute
  DoctorQueueRoute: typeof DoctorQueueRoute
  DoctorSubstitutionsRoute: typeof DoctorSubstitutionsRoute
  OnboardingDoctorRoute: typeof OnboardingDoctorRoute
  OnboardingPharmacyRoute: typeof OnboardingPharmacyRoute
  PharmacyFinanceRoute: typeof PharmacyFinanceRoute
  PharmacyNewRoute: typeof PharmacyNewRoute
  PharmacyOnboardingRoute: typeof PharmacyOnboardingRoute
  PharmacyPrescriptionsRoute: typeof PharmacyPrescriptionsRoute
  STokenRoute: typeof STokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PharmacyIndexRoute: typeof PharmacyIndexRoute
  DoctorConsultationsPublicIdRoute: typeof DoctorConsultationsPublicIdRoute
  PharmacyConsultationsPublicIdRoute: typeof PharmacyConsultationsPublicIdRoute
  VerifyKindCodeRoute: typeof VerifyKindCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/archive': {
      id: '/admin/archive'
      path: '/admin/archive'
      fullPath: '/admin/archive'
      preLoaderRoute: typeof AdminArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/admin/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quality': {
      id: '/admin/quality'
      path: '/admin/quality'
      fullPath: '/admin/quality'
      preLoaderRoute: typeof AdminQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/admin/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scheduling': {
      id: '/admin/scheduling'
      path: '/admin/scheduling'
      fullPath: '/admin/scheduling'
      preLoaderRoute: typeof AdminSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/earnings': {
      id: '/doctor/earnings'
      path: '/doctor/earnings'
      fullPath: '/doctor/earnings'
      preLoaderRoute: typeof DoctorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/membership': {
      id: '/doctor/membership'
      path: '/doctor/membership'
      fullPath: '/doctor/membership'
      preLoaderRoute: typeof DoctorMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/onboarding': {
      id: '/doctor/onboarding'
      path: '/doctor/onboarding'
      fullPath: '/doctor/onboarding'
      preLoaderRoute: typeof DoctorOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/queue': {
      id: '/doctor/queue'
      path: '/doctor/queue'
      fullPath: '/doctor/queue'
      preLoaderRoute: typeof DoctorQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/substitutions': {
      id: '/doctor/substitutions'
      path: '/doctor/substitutions'
      fullPath: '/doctor/substitutions'
      preLoaderRoute: typeof DoctorSubstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/doctor': {
      id: '/onboarding/doctor'
      path: '/onboarding/doctor'
      fullPath: '/onboarding/doctor'
      preLoaderRoute: typeof OnboardingDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/pharmacy': {
      id: '/onboarding/pharmacy'
      path: '/onboarding/pharmacy'
      fullPath: '/onboarding/pharmacy'
      preLoaderRoute: typeof OnboardingPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/': {
      id: '/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof PharmacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/finance': {
      id: '/pharmacy/finance'
      path: '/pharmacy/finance'
      fullPath: '/pharmacy/finance'
      preLoaderRoute: typeof PharmacyFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/new': {
      id: '/pharmacy/new'
      path: '/pharmacy/new'
      fullPath: '/pharmacy/new'
      preLoaderRoute: typeof PharmacyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/onboarding': {
      id: '/pharmacy/onboarding'
      path: '/pharmacy/onboarding'
      fullPath: '/pharmacy/onboarding'
      preLoaderRoute: typeof PharmacyOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/prescriptions': {
      id: '/pharmacy/prescriptions'
      path: '/pharmacy/prescriptions'
      fullPath: '/pharmacy/prescriptions'
      preLoaderRoute: typeof PharmacyPrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultations/$publicId': {
      id: '/doctor/consultations/$publicId'
      path: '/doctor/consultations/$publicId'
      fullPath: '/doctor/consultations/$publicId'
      preLoaderRoute: typeof DoctorConsultationsPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/consultations/$publicId': {
      id: '/pharmacy/consultations/$publicId'
      path: '/pharmacy/consultations/$publicId'
      fullPath: '/pharmacy/consultations/$publicId'
      preLoaderRoute: typeof PharmacyConsultationsPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$kind/$code': {
      id: '/verify/$kind/$code'
      path: '/verify/$kind/$code'
      fullPath: '/verify/$kind/$code'
      preLoaderRoute: typeof VerifyKindCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminArchiveRoute: AdminArchiveRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPayrollRoute: AdminPayrollRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminQualityRoute: AdminQualityRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminSchedulingRoute: AdminSchedulingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  DoctorEarningsRoute: DoctorEarningsRoute,
  DoctorMembershipRoute: DoctorMembershipRoute,
  DoctorOnboardingRoute: DoctorOnboardingRoute,
  DoctorQueueRoute: DoctorQueueRoute,
  DoctorSubstitutionsRoute: DoctorSubstitutionsRoute,
  OnboardingDoctorRoute: OnboardingDoctorRoute,
  OnboardingPharmacyRoute: OnboardingPharmacyRoute,
  PharmacyFinanceRoute: PharmacyFinanceRoute,
  PharmacyNewRoute: PharmacyNewRoute,
  PharmacyOnboardingRoute: PharmacyOnboardingRoute,
  PharmacyPrescriptionsRoute: PharmacyPrescriptionsRoute,
  STokenRoute: STokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  PharmacyIndexRoute: PharmacyIndexRoute,
  DoctorConsultationsPublicIdRoute: DoctorConsultationsPublicIdRoute,
  PharmacyConsultationsPublicIdRoute: PharmacyConsultationsPublicIdRoute,
  VerifyKindCodeRoute: VerifyKindCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
