/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PharmacyIndexRouteImport } from './routes/pharmacy.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PharmacyNewRouteImport } from './routes/pharmacy.new'
import { Route as PatientSessionIdRouteImport } from './routes/patient.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyIndexRoute = PharmacyIndexRouteImport.update({
  id: '/pharmacy/',
  path: '/pharmacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyNewRoute = PharmacyNewRouteImport.update({
  id: '/pharmacy/new',
  path: '/pharmacy/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientSessionIdRoute = PatientSessionIdRouteImport.update({
  id: '/patient/$sessionId',
  path: '/patient/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patient/$sessionId': typeof PatientSessionIdRoute
  '/pharmacy/new': typeof PharmacyNewRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patient/$sessionId': typeof PatientSessionIdRoute
  '/pharmacy/new': typeof PharmacyNewRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/pharmacy': typeof PharmacyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patient/$sessionId': typeof PatientSessionIdRoute
  '/pharmacy/new': typeof PharmacyNewRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patient/$sessionId'
    | '/pharmacy/new'
    | '/admin/'
    | '/doctor/'
    | '/pharmacy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patient/$sessionId'
    | '/pharmacy/new'
    | '/admin'
    | '/doctor'
    | '/pharmacy'
  id:
    | '__root__'
    | '/'
    | '/patient/$sessionId'
    | '/pharmacy/new'
    | '/admin/'
    | '/doctor/'
    | '/pharmacy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientSessionIdRoute: typeof PatientSessionIdRoute
  PharmacyNewRoute: typeof PharmacyNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  PharmacyIndexRoute: typeof PharmacyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/': {
      id: '/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof PharmacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/new': {
      id: '/pharmacy/new'
      path: '/pharmacy/new'
      fullPath: '/pharmacy/new'
      preLoaderRoute: typeof PharmacyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$sessionId': {
      id: '/patient/$sessionId'
      path: '/patient/$sessionId'
      fullPath: '/patient/$sessionId'
      preLoaderRoute: typeof PatientSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientSessionIdRoute: PatientSessionIdRoute,
  PharmacyNewRoute: PharmacyNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  PharmacyIndexRoute: PharmacyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
